version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:latest
        environment:
            - "MYSQL_ROOT_PASSWORD=guest"
            - "MYSQL_DATABASE=laravel_app"
        ports:
            - "33061:3306"
    composer:
        image: composer/composer
        volumes_from: 
            - web
        working_dir: /var/www
