#!/bin/bash -e

docker-compose up -d
docker-compose run composer install
docker-compose run app npm install
cat << 'EOF' >> .env
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost:8080
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=33061
DB_DATABASE=laravel_app
DB_USERNAME=root
DB_PASSWORD=guest
EOF
docker-compose run app php artisan key:generate
